### ISSUE TITLE
User Data - Set up fetch data call (GET)

### ISSUE THREAD

**Issue by ckoga** [spaceplesiosaur/refactor-tractor#10]
Getting data and making sure the tests still work might be another thing we want to set up early so that refactoring  goes smoothly.

**Comment by spaceplesiosaur** [comment]
@ckoga  Making 4 issues for fetch, one for each call we need to do.  This one will be for User Data.

 userData: https://fe-apps.herokuapp.com/api/v1/fitlit/1908/users/userData
