### ISSUE TITLE
Change divs to semantic tags

### ISSUE THREAD

**Issue by MattTuring** [spaceplesiosaur/refactor-tractor#11]
for example most content is in a div

**Comment by spaceplesiosaur** [comment]
ASSIGN THIS TO YOURSELF AND LABEL IN-PROGRESS

Find all divs in code that don't belong and change to semantic tags

**Comment by spaceplesiosaur** [comment]
@MattTuring I think you mentioned that this https://github.com/spaceplesiosaur/refactor-tractor/pull/39 closed this one as well.
