### ISSUE TITLE
Hydration Data - Set up fetch call

### ISSUE THREAD

**Issue by spaceplesiosaur** [spaceplesiosaur/refactor-tractor#14]
ASSIGN THIS TO YOURSELF AND LABEL IN-PROGRESS

hydrationData: https://fe-apps.herokuapp.com/api/v1/fitlit/1908/hydration/hydrationData

**Comment by MattTuring** [comment]
I am going to start this,  I will only set up one call and send out my code so everyone else can practice on the others

**Comment by MattTuring** [comment]
This has been completed
