### ISSUE TITLE
Background and foreground colors don't have sufficient contrast ratio

### ISSUE THREAD

**Issue by spaceplesiosaur** [spaceplesiosaur/refactor-tractor#5]
ASSIGN THIS TO YOURSELF AND LABEL IN-PROGRESS

<img width="1114" alt="Screen Shot 2019-10-17 at 9 31 48 PM" src="https://user-images.githubusercontent.com/24462031/67063888-9c4eba80-f125-11e9-831c-2f9c3db83417.png">

**Comment by MattTuring** [comment]
This is completed
