### ISSUE TITLE
Need lang attribute on HTML

### ISSUE THREAD

**Issue by spaceplesiosaur** [spaceplesiosaur/refactor-tractor#6]
ASSIGN THIS TO YOURSELF AND LABEL IN-PROGRESS

<img width="1114" alt="Screen Shot 2019-10-17 at 9 33 16 PM" src="https://user-images.githubusercontent.com/24462031/67063953-d029e000-f125-11e9-8008-00654ee9745e.png">

**Comment by MattTuring** [comment]
This has been completed
