### ISSUE TITLE
Math.floor or something similar needs to be added to Most Active functionality

### ISSUE THREAD

**Issue by spaceplesiosaur** [spaceplesiosaur/refactor-tractor#67]
<img width="423" alt="Screen Shot 2019-10-25 at 9 30 00 PM" src="https://user-images.githubusercontent.com/24462031/67613793-be23ef00-f76e-11e9-902b-b8ae7136c54d.png">

**Comment by ckoga** [comment]
@MattTuring I think you already fixed this with the bandaid fix, you are assigned to it because it should close with your next PR.

**Comment by spaceplesiosaur** [comment]
Closed with https://github.com/spaceplesiosaur/refactor-tractor/pull/83
