### ISSUE TITLE
Media queries - title needs to be centered and 'today' date needs to be fixed on smallest device size

### ISSUE THREAD

**Issue by spaceplesiosaur** [spaceplesiosaur/refactor-tractor#70]
<img width="495" alt="Screen Shot 2019-10-25 at 9 46 25 PM" src="https://user-images.githubusercontent.com/24462031/67613935-080dd480-f771-11e9-8575-77b53a18f516.png">

(Otherwise the responsiveness looks awesome, thanks @ckoga  and @MattTuring

**Comment by ckoga** [comment]
add media query for phone sizes we lose the logo and h1 is off center
