### ISSUE TITLE
Refactor WITHIN Activity class

### ISSUE THREAD

**Issue by spaceplesiosaur** [spaceplesiosaur/refactor-tractor#8]
ASSIGN THIS TO YOURSELF AND LABEL IN-PROGRESS

"Refactor within your classes to create dynamic methods that use arguments/parameters for changing their behavior"

See example below - there are functions that can likely be combined into one or two functions.

**Comment by MattTuring** [comment]
Adding another specific example:

  returnAverageMinutesActiveForWeek(week) {
    let specificUser = this.findUser();
    let weekOfData = this.returnWeekOfData(week, specificUser);
    return Math.floor(weekOfData.reduce((totalMinutes, eachDay) => {
      totalMinutes += eachDay.minutesActive
      return totalMinutes
    }, 0) / 7)
  }

  returnAverageStepsForWeek(week) {
    let specificUser = this.findUser();
    let weekOfData = this.returnWeekOfData(week, specificUser);
    return Math.floor(weekOfData.reduce((totalSteps, eachDay) => {
      totalSteps += eachDay.numSteps
      return totalSteps
    }, 0) / 7)
  }

  returnAverageStairsForWeek(week) {
    let specificUser = this.findUser();
    let weekOfData = this.returnWeekOfData(week, specificUser);
    return Math.floor(weekOfData.reduce((totalStairs, eachDay) => {
      totalStairs += eachDay.flightsOfStairs
      return totalStairs
    }, 0) / 7)
  }

**Comment by spaceplesiosaur** [comment]
See

**Comment by spaceplesiosaur** [comment]
Finished refactoring, testing, and adding to DOM.

**Comment by spaceplesiosaur** [comment]
Fixed with https://github.com/spaceplesiosaur/refactor-tractor/pull/33.  Closing.
