### ISSUE TITLE
CSS to SCSS - make index.scss file

### ISSUE THREAD

**Issue by ckoga** [spaceplesiosaur/refactor-tractor#9]
ASSIGN THIS TO YOURSELF AND LABEL IN-PROGRESS

Need to convert css file to a SCSS file and re-write css rules.

**Comment by groprog** [comment]
Hi @ckoga .
May I start  working on this?

**Comment by ckoga** [comment]
Hi Groprog!  This is actually a school project you are more than welcome to make a branch but we won't be merging anything you push until after we turn this in.  Have fun!!

**Comment by groprog** [comment]
Okay , got it .
I am a beginner too, I work on to figure out how sass work,

**Comment by ckoga** [comment]
Hey groprog, just finished talking to our instructors, I am sorry I had no idea how the good first issue label worked.  We won't be able to add you as a contributor until after we turn this project in.  Keep an eye on it and in about two weeks if you're still interested we can add you as a contributor.  Again sorry and thank you for showing interest!

**Comment by MattTuring** [comment]
This has been completed
